insert into users (id, login_name, password_hash, role_name) values (-1, 'user', 'PBKDF2WithHmacSHA256:2048:e9vXAAs/amAf2/PT/eVw2UbG6DcdtIZArf0FqMG8ClI=:UTOAQ8LsucZL3nua/RQj3VyDid3KhaSUFc5AaVI8T4A=', 'USER')
insert into users (id, login_name, password_hash, role_name) values (-2, 'manager', 'PBKDF2WithHmacSHA256:2048:e9vXAAs/amAf2/PT/eVw2UbG6DcdtIZArf0FqMG8ClI=:UTOAQ8LsucZL3nua/RQj3VyDid3KhaSUFc5AaVI8T4A=', 'MANAGER')
insert into users (id, login_name, password_hash, role_name) values (-3, 'admin', 'PBKDF2WithHmacSHA256:2048:e9vXAAs/amAf2/PT/eVw2UbG6DcdtIZArf0FqMG8ClI=:UTOAQ8LsucZL3nua/RQj3VyDid3KhaSUFc5AaVI8T4A=', 'ADMIN')

insert into authors (id, name, biography) values (-1, 'John Smit', 'Biography about author')
insert into authors (id, name, biography) values (-2, 'Brus Ekkel', 'Biography about author')
insert into authors (id, name, biography) values (-3, 'Brus Ekkel3', 'Biography about author')
insert into authors (id, name, biography) values (-4, 'Brus Ekkel4', 'Biography about author')
insert into authors (id, name, biography) values (-5, 'Brus Ekkel5', 'Biography about author')
insert into authors (id, name, biography) values (-6, 'Brus Ekkel6', 'Biography about author')
insert into authors (id, name, biography) values (-7, 'Brus Ekkel7', 'Biography about author')


insert into books (id, title, isbn, author_id, year) values (-1, 'One', '1234567', -1, 1995)
insert into books (id, title, isbn, author_id, year) values (-2, 'Two', '1234567', -2, 1995)
insert into books (id, title, isbn, author_id, year) values (-3, 'Three', '1234567', -2, 1980)
insert into books (id, title, isbn, author_id, year) values (-4, 'One2', '1234567', -1, 1995)
insert into books (id, title, isbn, author_id, year) values (-5, 'Two2', '1234567', -2, 1995)





insert into publishers (id, name, country, city, street, house) values (-1, 'SIA "Anta"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-2, 'SIA "Anta2"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-3, 'SIA "Anta3"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-4, 'SIA "Anta4"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-5, 'SIA "Anta5"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-6, 'SIA "Anta"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-7, 'SIA "Anta234"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-8, 'SIA "Anta33"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-9, 'SIA "Anta4"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-10, 'SIA "Anta5"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-11, 'SIA "Anta11111"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-12, 'SIA "Anta2342"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-13, 'SIA "Anta345"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-14, 'SIA "Anta4"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-15, 'SIA "Anta222222222222"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-16, 'SIA "Antafdg"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-17, 'SIA "Anta2fg"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-18, 'SIA "Anta365"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-19, 'SIA "Anta4gf"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-20, 'SIA "Anta545"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-21, 'SIA "Anta5dh"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-22, 'SIA "Anta5"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-23, 'SIA "Anta11111"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-24, 'SIA "Anta2342"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-25, 'SIA "Anta345"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-26, 'SIA "Anta4"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-27, 'SIA "Anta655"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-28, 'SIA "Antafdg"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-29, 'SIA "Anta2fg"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-30, 'SIA "Anta365"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-31, 'SIA "Anta4gf"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-32, 'SIA "Anta545"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-33, 'SIA "Anta5dh"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-34, 'SIA "Anta545"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-35, 'SIA "Anta5dh"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-36, 'SIA "Anta5"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-37, 'SIA "Anta11111"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-38, 'SIA "Anta2342"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-39, 'SIA "Anta345"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-40, 'SIA "Anta4"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-41, 'SIA "Anta655"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-42, 'SIA "Antafdg"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-43, 'SIA "Anta2fg"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-44, 'SIA "Anta365"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-45, 'SIA "Anta4gf"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-46, 'SIA "Anta545"', 'Latvia', 'Riga', 'Marupes', '47')
insert into publishers (id, name, country, city, street, house) values (-47, 'SIA "Anta5dh"', 'Latvia', 'Riga', 'Marupes', '47')